[versions]
agp = "9.3.1"
coreKtx = "1.10.1"
webgpu = "1.0.0-alpha05"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-webgpu = { group = "androidx.webgpu", name = "webgpu", version.ref = "webgpu" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
